name: emb3rs-business-module
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - attrs=21.2.0
  - black=19.10b0
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - click=8.0.3
  - colorama=0.4.4
  - cycler=0.11.0
  - freetype=2.10.4
  - importlib-metadata=4.8.2
  - jpeg=9d
  - kiwisolver=1.3.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.0.10
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - matplotlib-base=3.3.4
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - numpy=1.20.3
  - numpy-financial=1.0.0
  - olefile=0.46
  - openssl=1.1.1l
  - pathspec=0.7.0
  - pillow=6.2.1
  - pip=21.2.2
  - pyparsing=3.0.6
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - readline=8.1
  - regex=2021.8.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - xz=5.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
