name: emb3rs-business-module
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - attrs=21.2.0
  - black=19.10b0
  - blas=1.0
  - brotli=1.0.9
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - click=8.0.3
  - colorama=0.4.4
  - cycler=0.10.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - numpy-financial=1.0.0
  - olefile=0.46
  - openssl=1.1.1l
  - pathspec=0.7.0
  - pillow=8.4.0
  - pip=21.2.4
  - pyparsing=3.0.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - readline=8.1
  - regex=2021.8.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
